In [55]:
library(dplyr)
library(units)
library(terra)
library(readxl)

In [2]:


here::i_am("examples/Calculate-areas-per-EFG.ipynb")

here() starts at /Users/z3529065/proyectos/EIW/ecosystems-map-synthesis

In [52]:
data_dir <- here::here("gisdata", "AUS", "NEAP")
dir(data_dir)

[1] "Crosswalks"
[2] "Freshwater Rivers and streams biome"
[3] "Geofabric-derived input data"
[4] "Marine Pelagic ocean waters biome"
[5] "Marine-Freshwater-Terrestrial-Transitional"
[6] "NVIS-derived input data"

In [53]:
data_dir <- here::here("gisdata", "AUS", "NEAP", "Crosswalks")
dir(data_dir)

[1] "ALUM-IUCNGET.xlsx"        "Estuarine-IUCNGET.xlsx"
[3] "Lacustrine-IUCNGET.xlsx"  "Marine-IUCNGET.xlsx"
[5] "Pelagic-IUCNGET.xlsx"     "Riverine-IUCNGET.xlsx"
[7] "Rivers-IUCNGET.xlsx"      "Springs-IUCNGET.xlsx"
[9] "Terrestrial_IUCNGET.xlsx"

In [81]:
springs <- read_excel(here::here(data_dir,'Springs-IUCNGET.xlsx'), sheet=3) |> pull(`sssom:object_label`) |> unique()

In [82]:
rivers <- read_excel(here::here(data_dir,'Rivers-IUCNGET.xlsx'), sheet=3) |> pull(`sssom:object_label`) |> unique()

In [83]:
lacustrine <- read_excel(here::here(data_dir,'Lacustrine-IUCNGET.xlsx'), sheet=3) |> pull(`sssom:object_label`) |> unique()

In [85]:
marine <- read_excel(here::here(data_dir,'Marine-IUCNGET.xlsx'), sheet=3) |> pull(`sssom:object_label`) |> unique()

In [88]:
estuarine <- read_excel(here::here(data_dir,'Estuarine-IUCNGET.xlsx'), sheet=3) |> pull(`sssom:object_label`) |> unique()

In [86]:
pelagic <- read_excel(here::here(data_dir,'Pelagic-IUCNGET.xlsx'), sheet=2) |> pull(`Functional Group (Level 3)`)

In [87]:
terrestrial <- read_excel(here::here(data_dir,'Terrestrial_IUCNGET.xlsx'), sheet=3) |> pull(`sssom:object_label`) |> unique()

In [84]:
constructed <- read_excel(here::here(data_dir,'ALUM-IUCNGET.xlsx'), sheet=3) |> pull(`sssom:object_label`) |> unique()

In [91]:
todos <- unique(c(springs,rivers,lacustrine,marine,estuarine,pelagic,terrestrial,constructed)) |> sort()
length(todos)

[1] 81

In [100]:
grep("^F[1-3]|TF1",todos, value=TRUE)
grep("^M|^FM",todos, value=TRUE)
grep("^T[1-7]",todos, value=TRUE)

 [1] "F1.1 Permanent upland streams"
 [2] "F1.2 Permanent lowland rivers"
 [3] "F1.3 Freeze-thaw rivers and streams"
 [4] "F1.4 Seasonal upland streams"
 [5] "F1.5 Seasonal lowland rivers"
 [6] "F1.6 Episodic arid rivers"
 [7] "F2.1 Large permanent freshwater lakes"
 [8] "F2.10 Subglacial lakes"
 [9] "F2.2 Small permanent freshwater lakes"
[10] "F2.3 Seasonal freshwater lakes"
[11] "F2.4 Freeze-thaw freshwater lakes"
[12] "F2.5 Ephemeral freshwater lakes"
[13] "F2.6 Permanent salt and soda lakes"
[14] "F2.7 Ephemeral salt lakes"
[15] "F2.8 Artesian springs and oases"
[16] "F2.9 Geothermal pools and wetlands"
[17] "F3.1 Large reservoirs"
[18] "F3.2 Constructed lacustrine wetlands"
[19] "F3.3 Rice paddies"
[20] "F3.4 Freshwater aquafarms"
[21] "F3.5 Canals, ditches and drains"
[22] "TF1.1 Tropical flooded forests and peat forests"
[23] "TF1.2 Subtropical/temperate forested wetlands"
[24] "TF1.3 Permanent marshes"
[25] "TF1.4 Seasonal floodplain marshes"
[26] "TF1.5 Episodic arid floodplains"
[27] "TF1.6 Boreal, temperate and montane peat bogs"
[28] "TF1.7 Boreal and temperate fens"

 [1] "FM1.2 Permanently open riverine estuaries and bays"
 [2] "FM1.3 Intermittently closed and open lakes and lagoons"
 [3] "M1.1 Seagrass meadows"
 [4] "M1.10 Rhodolith/Maërl beds"
 [5] "M1.2 Kelp forests"
 [6] "M1.3 Photic coral reefs"
 [7] "M1.4 Shellfish beds and reefs"
 [8] "M1.5 Photo-limited marine animal forests"
 [9] "M1.6 Subtidal rocky reefs"
[10] "M1.7 Subtidal sand beds"
[11] "M1.8 Subtidal mud plains"
[12] "M2.1 Epipelagic ocean waters"
[13] "M2.2 Mesopelagic ocean water"
[14] "M2.3 Bathypelagic ocean waters"
[15] "M2.4 Abyssopelagic ocean waters"
[16] "M3.1 Continental and island slopes"
[17] "M3.2 Submarine canyons"
[18] "M3.3 Abyssal plains"
[19] "M3.4 Seamounts, ridges and plateaus"
[20] "MFT1.2 Intertidal forests and shrublands"
[21] "MFT1.3 Coastal saltmarshes and reedbeds"
[22] "MT1.1 Rocky Shorelines"
[23] "MT1.2 Muddy Shorelines"
[24] "MT1.3 Sandy Shorelines"
[25] "MT1.4 Boulder and cobble shores"
[26] "MT2.1 Coastal shrublands and grasslands"
[27] "MT2.2 Large seabird and pinniped colonies"
[28] "MT3.1 Artificial shorelines"

 [1] "T1.1 Tropical/Subtropical lowland rainforests"
 [2] "T1.2 Tropical/Subtropical dry forests and thickets"
 [3] "T1.3 Tropical/Subtropical montane rainforests"
 [4] "T2.1 Boreal and temperate high montane forests and woodlands"
 [5] "T2.3 Oceanic cool temperate rainforests"
 [6] "T2.4 Warm temperate laurophyll forests"
 [7] "T2.5 Temperate pyric humid forests"
 [8] "T2.6 Temperate pyric sclerophyll forests and woodlands"
 [9] "T3.1 Seasonally dry tropical shrublands"
[10] "T3.2 Seasonally dry temperate heath and shrublands"
[11] "T4.2 Pyric tussock savannas"
[12] "T4.3 Hummock savannas"
[13] "T4.4 Temperate woodlands"
[14] "T4.5 Temperate subhumid grasslands"
[15] "T5.1 Semi-desert steppe"
[16] "T5.3 Sclerophyll hot deserts and semi-deserts"
[17] "T5.6 Semi-arid open woodlands"
[18] "T6.3 Polar tundra and deserts"
[19] "T6.4 Temperate alpine grasslands and shrublands"
[20] "T7.1 Annual croplands"
[21] "T7.2 Sown pastures and fields"
[22] "T7.3 Plantations"
[23] "T7.4 Urban and industrial ecosystems"
[24] "T7.5 Derived semi-natural pastures and old fields"

character(0)

In [3]:
data_dir <- here::here("gisdata", "AUS", "NEAP", "NVIS-derived input data")
dir(data_dir)

[1] "GET_NVIS_Extant_100m.tif"          "GET_NVIS_Extant_100m.tif.aux.xml"
[3] "GET_NVIS_Pre1750_100m.tif"         "GET_NVIS_Pre1750_100m.tif.aux.xml"
[5] "maps"                              "NVIS_IUCNGET.xlsx"

In [4]:
raster_file <- here::here(data_dir, "GET_NVIS_Pre1750_100m.tif")
r0 <- rast(raster_file)
raster_file <- here::here(data_dir, "GET_NVIS_Extant_100m.tif")
r1 <- rast(raster_file)

In [5]:
r0

class       : SpatRaster
size        : 38360, 40090, 1  (nrow, ncol, nlyr)
resolution  : 100, 100  (x, y)
extent      : -1887000, 2122000, -4840000, -1004000  (xmin, xmax, ymin, ymax)
coord. ref. : GDA94 / Australian Albers (EPSG:3577)
source      : GET_NVIS_Pre1750_100m.tif
categories  : Ecosystem_functional_group, Realm, Biome, Group_ID
name        :    Ecosystem_functional_group
min value   : F1.1 Permanent upland streams
max value   :         M1.1 Seagrass meadows

In [6]:
cats(r0)

[[1]]
   Value                             Ecosystem_functional_group
1      1                          F1.1 Permanent upland streams
2      3                    F1.3 Freeze-thaw rivers and streams
3      5                           F1.5 Seasonal lowland rivers
4      6                              F1.6 Episodic arid rivers
5      9                  F2.2 Small permanent freshwater lakes
6     10                         F2.3 Seasonal freshwater lakes
7     12                        F2.5 Ephemeral freshwater lakes
8     13                     F2.6 Permanent salt and soda lakes
9     14                              F2.7 Ephemeral salt lakes
10    24     FM1.2 Permanently open riverine estuaries and bays
11    25 FM1.3 Intermittently closed and open lakes and lagoons
12    27               MFT1.2 Intertidal forests and shrublands
13    28                MFT1.3 Coastal saltmarshes and reedbeds
14    30                                 MT1.2 Muddy Shorelines
15    31                                 MT1.3 Sandy Shorelines
16    33                MT2.1 Coastal shrublands and grasslands
17    34              MT2.2 Large seabird and pinniped colonies
18    36          T1.1 Tropical/Subtropical lowland rainforests
19    37     T1.2 Tropical/Subtropical dry forests and thickets
20    38          T1.3 Tropical/Subtropical montane rainforests
21    42                T2.3 Oceanic cool temperate rainforests
22    43                 T2.4 Warm temperate laurophyll forests
23    44                     T2.5 Temperate pyric humid forests
24    45 T2.6 Temperate pyric sclerophyll forests and woodlands
25    46                T3.1 Seasonally dry tropical shrublands
26    47     T3.2 Seasonally dry temperate heath and shrublands
27    51                            T4.2 Pyric tussock savannas
28    52                                  T4.3 Hummock savannas
29    53                               T4.4 Temperate woodlands
30    54                     T4.5 Temperate subhumid grasslands
31    55                                T5.1 Semi-desert steppe
32    57          T5.3 Sclerophyll hot deserts and semi-deserts
33    60                          T5.6 Semi-arid open woodlands
34    64        T6.4 Temperate alpine grasslands and shrublands
35    71        TF1.1 Tropical flooded forests and peat forests
36    72          TF1.2 Subtropical/temperate forested wetlands
37    73                                TF1.3 Permanent marshes
38    74                      TF1.4 Seasonal floodplain marshes
39    75                        TF1.5 Episodic arid floodplains
40    76          TF1.6 Boreal, temperate and montane peat bogs
41    77                        TF1.7 Boreal and temperate fens
42    78                                  M1.1 Seagrass meadows
                           Realm                                        Biome
1                     Freshwater                     Rivers and streams biome
2                     Freshwater                     Rivers and streams biome
3                     Freshwater                     Rivers and streams biome
4                     Freshwater                     Rivers and streams biome
5                     Freshwater                                  Lakes biome
6                     Freshwater                                  Lakes biome
7                     Freshwater                                  Lakes biome
8                     Freshwater                                  Lakes biome
9                     Freshwater                                  Lakes biome
10             Freshwater-Marine      Semi-confined transitional waters biome
11             Freshwater-Marine      Semi-confined transitional waters biome
12 Marine-Freshwater-Terrestrial                         Brackish tidal biome
13 Marine-Freshwater-Terrestrial                         Brackish tidal biome
14            Marine-Terrestrial                             Shorelines biome
15            Marine-Terrestrial                             Shorelines biome
16            Marine-Terrestrial                  Supralittoral coastal biome
17            Marine-Terrestrial                  Supralittoral coastal biome
18                   Terrestrial           Tropical-subtropical forests biome
19                   Terrestrial           Tropical-subtropical forests biome
20                   Terrestrial           Tropical-subtropical forests biome
21                   Terrestrial Temperate-boreal forests and woodlands biome
22                   Terrestrial Temperate-boreal forests and woodlands biome
23                   Terrestrial Temperate-boreal forests and woodlands biome
24                   Terrestrial Temperate-boreal forests and woodlands biome
25                   Terrestrial       Shrublands and shrubby woodlands biome
26                   Terrestrial       Shrublands and shrubby woodlands biome
27                   Terrestrial                Savannas and grasslands biome
28                   Terrestrial                Savannas and grasslands biome
29                   Terrestrial                Savannas and grasslands biome
30                   Terrestrial                Savannas and grasslands biome
31                   Terrestrial               Deserts and semi-deserts biome
32                   Terrestrial               Deserts and semi-deserts biome
33                   Terrestrial               Deserts and semi-deserts biome
34                   Terrestrial               Polar/alpine (cryogenic) biome
35        Terrestrial-Freshwater                    Palustrine wetlands biome
36        Terrestrial-Freshwater                    Palustrine wetlands biome
37        Terrestrial-Freshwater                    Palustrine wetlands biome
38        Terrestrial-Freshwater                    Palustrine wetlands biome
39        Terrestrial-Freshwater                    Palustrine wetlands biome
40        Terrestrial-Freshwater                    Palustrine wetlands biome
41        Terrestrial-Freshwater                    Palustrine wetlands biome
42                        Marine                           Marine shelf biome
   Group_ID
1      F1.1
2      F1.3
3      F1.5
4      F1.6
5      F2.2
6      F2.3
7      F2.5
8      F2.6
9      F2.7
10    FM1.2
11    FM1.3
12   MFT1.2
13   MFT1.3
14    MT1.2
15    MT1.3
16    MT2.1
17    MT2.2
18     T1.1
19     T1.2
20     T1.3
21     T2.3
22     T2.4
23     T2.5
24     T2.6
25     T3.1
26     T3.2
27     T4.2
28     T4.3
29     T4.4
30     T4.5
31     T5.1
32     T5.3
33     T5.6
34     T6.4
35    TF1.1
36    TF1.2
37    TF1.3
38    TF1.4
39    TF1.5
40    TF1.6
41    TF1.7
42     M1.1

# Calcular tabla de frecuencias

In [9]:
frequencies_pre <- freq(r0)

In [10]:
frequencies_post <- freq(r1)

In [11]:
total_pre_count <- sum(frequencies_pre$count)
total_post_count <- sum(frequencies_post$count)

In [12]:
total_pre_count/total_post_count

[1] 0.997787

In [17]:

efg_freq_tables <- frequencies_pre |> 
    left_join(frequencies_post, by='value') |>
    transmute(value,
              `Proportion Pre 1750`=set_units(count.x *100/total_pre_count, "%"),
              `Proportion Extant`=set_units(count.y * 100/total_post_count, "%"))

r_sub <- r0
r_sub[!(r_sub %in% slc_names)] <- NA

# Calculate area of each category
expanse(r_sub, unit="km", byValue=TRUE)

# Filter for selected functional groups

In [7]:
slc <- c(44:47,51:54,60)

In [8]:
slc_names <- cats(r0)[[1]] |> filter(Value %in% slc) |> pull(Ecosystem_functional_group)

In [18]:
efg_freq_tables |>
filter(value %in% slc_names)

  value                                                  Proportion Pre 1750
1 T2.5 Temperate pyric humid forests                      1.03565871 [%]
2 T2.6 Temperate pyric sclerophyll forests and woodlands  4.78783226 [%]
3 T3.1 Seasonally dry tropical shrublands                 0.03113105 [%]
4 T3.2 Seasonally dry temperate heath and shrublands      2.09321127 [%]
5 T4.2 Pyric tussock savannas                            12.29672535 [%]
6 T4.3 Hummock savannas                                   7.08232022 [%]
7 T4.4 Temperate woodlands                                4.10610744 [%]
8 T4.5 Temperate subhumid grasslands                      5.53500767 [%]
9 T5.6 Semi-arid open woodlands                          10.78180152 [%]
  Proportion Extant
1  0.93825690 [%]
2  2.34115405 [%]
3  0.09386542 [%]
4  1.01252976 [%]
5 10.95132537 [%]
6  6.19485366 [%]
7  1.56392465 [%]
8  4.92339132 [%]
9  7.16894939 [%]

In [41]:
query_freq_table <- function (qry) 
{
    brks <- set_units(c(0, 1, 5, 10, 15, 100), "%")
    lbls <- c("<1%", "<5%", "5–10%", ">10%", ">15%")
    slc_names <- pull(filter(cats(r0)[[1]], qry), Ecosystem_functional_group)
    tbl <- transmute(filter(efg_freq_tables, value %in% slc_names), 
        `EFG name` = value, `Proportion Pre 1750 (NEAP GET L3 map)` = cut(coalesce(`Proportion Pre 1750`, 
            set_units(0.01, "%")), brks, lbls), `Proportion Extant (NEAP GET L3 map)` = cut(coalesce(`Proportion Extant`, 
            set_units(0.01, "%")), brks, lbls))
    return(tbl)
}

# Freshwater

In [49]:
query_freq_table(cats(r0)[[1]]$Realm %in% c("Freshwater","Terrestrial-Freshwater")) |> write.csv("freshwater.csv")

# Terrestrial

In [50]:
 query_freq_table(cats(r0)[[1]]$Realm %in% c("Terrestrial")) |> write.csv("terrestrial.csv")

# Marine

In [51]:
 query_freq_table(cats(r0)[[1]]$Realm %in% c("Marine-Freshwater-Terrestrial","Marine","Marine-Terrestrial","Freshwater-Marine")) |> write.csv("marine.csv")