In [1]:
import pyprojroot
#import os
#import requests
#from pathlib import Path
#import pandas as pd
import geopandas as gpd
#import numpy as np

In [2]:
repodir = pyprojroot.find_root(pyprojroot.has_dir(".git"))

In [3]:
datadir = repodir /  'gisdata' / 'AUS' / 'NVIS'

In [4]:
nvis_det = gpd.read_file(repodir /  'gisdata' / 'AUS' / 'NVIS' / 'NVIS_V7_0_VECTOR_STATE_FILES_EXT.gdb',
                    layer = 'NVIS7_0_LUT_AUST_DETAIL')

In [5]:
nvis_lut = gpd.read_file(repodir /  'gisdata' / 'AUS' / 'NVIS' / 'NVIS_V7_0_VECTOR_STATE_FILES_EXT.gdb',
                    layer = 'NVIS7_0_LUT_AUST_FLAT')

In [15]:
nvis_lut.columns

Index(['NVIS_ID', 'LEVEL_OF_DETAIL', 'NUMBER_OF_STRATA', 'DOMINANT_STRATUM',
       'U_SPECIES1', 'U_SPECIES2', 'U_SPECIES3', 'U_GENUS1',
       'U_GENUS1_DOMINANT', 'U_GENUS2', 'U_GENUS2_DOMINANT', 'U_GENUS3',
       'U_GENUS3_DOMINANT', 'U_GENUS_MIXED_FLAG', 'U_GROWTH_FORM1',
       'U_GROWTH_FORM2', 'U_GROWTH_FORM3', 'U_DOMINANT_GROWTH_FORM',
       'U_HEIGHT_CLASS', 'U_HEIGHT_RANGE', 'U_COVER_CODE', 'U_CROWN_COVER',
       'U_FOLIAGE_COVER', 'M_SPECIES1', 'M_SPECIES2', 'M_SPECIES3', 'M_GENUS1',
       'M_GENUS1_DOMINANT', 'M_GENUS2', 'M_GENUS2_DOMINANT', 'M_GENUS3',
       'M_GENUS3_DOMINANT', 'M_GENUS_MIXED_FLAG', 'M_GROWTH_FORM1',
       'M_GROWTH_FORM2', 'M_GROWTH_FORM3', 'M_DOMINANT_GROWTH_FORM',
       'M_HEIGHT_CLASS', 'M_HEIGHT_RANGE', 'M_COVER_CODE', 'M_CROWN_COVER',
       'M_FOLIAGE_COVER', 'G_SPECIES1', 'G_SPECIES2', 'G_SPECIES3', 'G_GENUS1',
       'G_GENUS1_DOMINANT', 'G_GENUS2', 'G_GENUS2_DOMINANT', 'G_GENUS3',
       'G_GENUS3_DOMINANT', 'G_GENUS_MIXED_FLAG', 'G_GROWTH_FORM1',
       'G_GROWTH_FORM2', 'G_GROWTH_FORM3', 'G_DOMINANT_GROWTH_FORM',
       'G_HEIGHT_CLASS', 'G_HEIGHT_RANGE', 'G_COVER_CODE', 'G_CROWN_COVER',
       'G_FOLIAGE_COVER', 'L5_ASSOCIATION', 'MVG_NUMBER', 'MVG_NAME',
       'MVS_NUMBER', 'MVS_NAME'],
      dtype='str')

In [58]:
target_species = 'Corymbia citriodora'
target_species = 'Eucalyptus dives'

In [79]:
ss = (nvis_lut == target_species).any(axis=1)
qry = nvis_lut.loc[ss,'NVIS_ID']

In [80]:
sum(ss)

1842

In [81]:
len(qry)

1842

In [69]:
ss1=nvis_lut.M_SPECIES1 == target_species
ss2=nvis_lut.M_SPECIES2 == target_species
ss3=nvis_lut.M_SPECIES3 == target_species

In [71]:
ss1=nvis_lut.G_SPECIES1 == target_species
ss2=nvis_lut.G_SPECIES2 == target_species
ss3=nvis_lut.G_SPECIES3 == target_species
qry = nvis_lut.loc[ss1 | ss2 | ss3,'NVIS_ID']

In [60]:
clmns = ['MVG_NAME',		'MVS_NAME', 'L5_ASSOCIATION']
aggfunc={''}
nvis_lut.loc[ss1 | ss2 | ss3,clmns]

,MVG_NAME,MVS_NAME,L5_ASSOCIATION
76,Eucalypt Open Forests,Eucalyptus tall open forests and open forests ...,"U+ ^Eucalyptus radiata s.l.,Eucalyptus dives\^..."
379,Eucalypt Open Forests,Eucalyptus tall open forests and open forests ...,"U+ ^Eucalyptus dives,Eucalyptus macrorhyncha,E..."
380,Eucalypt Open Forests,Eucalyptus open forests with a shrubby underst...,"U+ ^Eucalyptus dives,Eucalyptus dalrympleana s..."
678,Eucalypt Woodlands,"Eucalyptus woodlands with ferns, herbs, sedges...","U+ ^Eucalyptus croajingolensis,Eucalyptus rubi..."
772,Eucalypt Woodlands,Eucalyptus woodlands with a tussock grass unde...,"U+ ^Eucalyptus macrorhyncha,Eucalyptus dives,E..."
...,...,...,...
16055,Heathlands,Heathlands,"U ^Eucalyptus dives,Eucalyptus pauciflora,Euca..."
16355,Eucalypt Tall Open Forests,Eucalyptus open forests with a grassy understorey,"U+ ^Eucalyptus dives,Eucalyptus macrorhyncha,E..."
16534,Eucalypt Tall Open Forests,Eucalyptus tall open forest with a fine-leaved...,"U+ ^Eucalyptus dives,Eucalyptus dalrympleana,E..."
16603,Eucalypt Tall Open Forests,Eucalyptus open forests with a grassy understorey,"U+ ^Eucalyptus dives,Eucalyptus dalrympleana,E..."
16653,Eucalypt Open Forests,Eucalyptus open forests with a shrubby underst...,"U+ ^Eucalyptus dives,Eucalyptus rubida,Eucalyp..."

In [84]:
nvis_lut.groupby('U_SPECIES1').agg({'NVIS_ID':'nunique'}).sort_values('NVIS_ID',ascending=False)

                          NVIS_ID
U_SPECIES1
Eucalyptus dives              758
Eucalyptus bridgesiana        666
Eucalyptus pauciflora         582
Eucalyptus melliodora         506
Eucalyptus nortonii           476
...                           ...
Eucalyptus cooperiana           1
Eucalyptus confertiflora        1
Eucalyptus comitaevallis        1
Eucalyptus candida              1
Xylocarpus granatum             1

[985 rows x 1 columns]

All states

In [6]:
nvis_qld = gpd.read_file(repodir /  'gisdata' / 'AUS' / 'NVIS' / 'NVIS_V7_0_VECTOR_STATE_FILES_EXT.gdb',
                    layer = 'NVIS7_0_AUST_EXT_QLD', ignore_geometry=True)

In [7]:
nvis_tas = gpd.read_file(repodir /  'gisdata' / 'AUS' / 'NVIS' / 'NVIS_V7_0_VECTOR_STATE_FILES_EXT.gdb',
                    layer = 'NVIS7_0_AUST_EXT_TAS', ignore_geometry=True)

In [8]:
nvis_act = gpd.read_file(repodir /  'gisdata' / 'AUS' / 'NVIS' / 'NVIS_V7_0_VECTOR_STATE_FILES_EXT.gdb',
                    layer = 'NVIS7_0_AUST_EXT_ACT', ignore_geometry=True)

/Users/z3529065/proyectos/EIW/ecosystems-map-synthesis/.venv/lib/python3.13/site-packages/pyogrio/raw.py:200: UserWarning: Measured (M) geometry types are not supported. Original type 'Measured 3D MultiPolygon' is converted to 'MultiPolygon Z'
  return ogr_read(

In [9]:
nvis_vic = gpd.read_file(repodir /  'gisdata' / 'AUS' / 'NVIS' / 'NVIS_V7_0_VECTOR_STATE_FILES_EXT.gdb',
                    layer = 'NVIS7_0_AUST_EXT_VIC', ignore_geometry=True)

In [10]:
nvis_nt = gpd.read_file(repodir /  'gisdata' / 'AUS' / 'NVIS' / 'NVIS_V7_0_VECTOR_STATE_FILES_EXT.gdb',
                    layer = 'NVIS7_0_AUST_EXT_NT', ignore_geometry=True)

In [11]:
nvis_nsw = gpd.read_file(repodir /  'gisdata' / 'AUS' / 'NVIS' / 'NVIS_V7_0_VECTOR_STATE_FILES_EXT.gdb',
                    layer = 'NVIS7_0_AUST_EXT_NSW', ignore_geometry=True)

In [12]:
nvis_wa = gpd.read_file(repodir /  'gisdata' / 'AUS' / 'NVIS' / 'NVIS_V7_0_VECTOR_STATE_FILES_EXT.gdb',
                    layer = 'NVIS7_0_AUST_EXT_WA', ignore_geometry=True)

In [13]:
nvis_sa = gpd.read_file(repodir /  'gisdata' / 'AUS' / 'NVIS' / 'NVIS_V7_0_VECTOR_STATE_FILES_EXT.gdb',
                    layer = 'NVIS7_0_AUST_EXT_SA', ignore_geometry=True)

In [14]:
nvis_qld.head()

,MAPUNT_IDENTIFIER,NO_VEG_DESC,SPATIAL_MIX,NVISDSC1,NVISDSC2,NVISDSC3,NVISDSC4,NVISDSC5,NVISDSC6,VEGPROP1,VEGPROP2,VEGPROP3,VEGPROP4,VEGPROP5,VEGPROP6,DATA_SET_NUMBER,Shape_Length,Shape_Area
0,49300001,1,pure,40003,NaN,NaN,NaN,NaN,NaN,100,0,0,0,0,0,493,744.819069,22846.669202
1,49300003,1,pure,40013,NaN,NaN,NaN,NaN,NaN,100,0,0,0,0,0,493,2532.783728,329740.760841
2,49300003,1,pure,40013,NaN,NaN,NaN,NaN,NaN,100,0,0,0,0,0,493,3221.306102,158238.257063
3,49300003,1,pure,40013,NaN,NaN,NaN,NaN,NaN,100,0,0,0,0,0,493,2113.566259,190882.037094
4,49300003,1,pure,40013,NaN,NaN,NaN,NaN,NaN,100,0,0,0,0,0,493,988.678523,37111.096819

In [8]:
nvis_qld.groupby(['DATA_SET_NUMBER','SPATIAL_MIX',]).agg({'MAPUNT_IDENTIFIER': 'nunique'})

                                 MAPUNT_IDENTIFIER
DATA_SET_NUMBER SPATIAL_MIX
493             dominant mosaic              27793
                equal mosaic                  3309
                other mosaic                 21638
                pure                          2638

In [9]:
number_of_rows = nvis_qld.shape[0]
unique_mapunits = len(nvis_qld.MAPUNT_IDENTIFIER.unique())
y1 = [x for x in nvis_qld.NVISDSC1.unique()]
main_nvisdsc=len(y1)
for slc in ['NVISDSC2','NVISDSC3','NVISDSC4','NVISDSC5','NVISDSC6',]:
    for x in nvis_qld[slc].unique():
          if x not in y1:
              y1.append(x)
all_nvisdsc=len(y1)

In [10]:
print(f"NVIS dataset for QLD has {number_of_rows} rows with {unique_mapunits} unique map units.")
print(f"There are {main_nvisdsc} main NVISDSC units and a total of {all_nvisdsc} NVISDSC units.")

NVIS dataset for QLD has 732316 rows with 55378 unique map units.
There are 2712 main NVISDSC units and a total of 2754 NVISDSC units.

In [11]:
nvis_lut.loc[nvis_lut.NVIS_ID==40403]

,NVIS_ID,LEVEL_OF_DETAIL,NUMBER_OF_STRATA,DOMINANT_STRATUM,U_SPECIES1,U_SPECIES2,U_SPECIES3,U_GENUS1,U_GENUS1_DOMINANT,U_GENUS2,...,G_HEIGHT_CLASS,G_HEIGHT_RANGE,G_COVER_CODE,G_CROWN_COVER,G_FOLIAGE_COVER,L5_ASSOCIATION,MVG_NUMBER,MVG_NAME,MVS_NUMBER,MVS_NAME
17311,40403,level6_sub_association,3,U,Corymbia citriodora,Eucalyptus crebra,Corymbia hendersonii,Corymbia,Dom,Eucalyptus,...,2.0,0.5-1 m,i,20-50,10-30,U+ ^Corymbia citriodora+/-Eucalyptus crebra+/-...,3,Eucalypt Open Forests,5,Eucalyptus open forests with a grassy understorey

In [18]:
nvis_lut.loc[ss3]

,NVIS_ID,LEVEL_OF_DETAIL,NUMBER_OF_STRATA,DOMINANT_STRATUM,U_SPECIES1,U_SPECIES2,U_SPECIES3,U_GENUS1,U_GENUS1_DOMINANT,U_GENUS2,...,G_HEIGHT_CLASS,G_HEIGHT_RANGE,G_COVER_CODE,G_CROWN_COVER,G_FOLIAGE_COVER,L5_ASSOCIATION,MVG_NUMBER,MVG_NAME,MVS_NUMBER,MVS_NAME
15294,41539,level6_sub_association,4,U,Eucalyptus carnea,Eucalyptus tindaliae,Corymbia citriodora,Eucalyptus,Dom,,...,2.0,0.5-1 m,c,50-80,30-70,U+ +/-^Eucalyptus carnea+/-Eucalyptus tindalia...,3,Eucalypt Open Forests,5,Eucalyptus open forests with a grassy understorey
16326,43276,level6_sub_association,1,U,Eucalyptus moluccana,Eucalyptus crebra,Corymbia citriodora,Eucalyptus,Dom,,...,NaN,NaN,NaN,NaN,NaN,"U+ ^Eucalyptus moluccana,Eucalyptus crebra+/-C...",5,Eucalypt Woodlands,9,Eucalyptus woodlands with a tussock grass unde...
16694,42638,level6_sub_association,2,U,Eucalyptus moluccana,Eucalyptus drepanophylla,Corymbia citriodora,Eucalyptus,Dom,,...,1.0,<0.5 m,i,20-50,10-30,U+ ^Eucalyptus moluccana+/-Eucalyptus drepanop...,5,Eucalypt Woodlands,9,Eucalyptus woodlands with a tussock grass unde...
16965,41089,level6_sub_association,5,U,Corymbia clarksoniana,Eucalyptus portuensis,Corymbia citriodora,Corymbia,Dom,Eucalyptus,...,2.0,0.5-1 m,c,50-80,30-70,U+ ^Corymbia clarksoniana+/-Eucalyptus portuen...,5,Eucalypt Woodlands,9,Eucalyptus woodlands with a tussock grass unde...
17086,42778,level6_sub_association,6,U,Eucalyptus exilipes,Corymbia peltata,Corymbia citriodora,Eucalyptus,Dom,Corymbia,...,2.0,0.5-1 m,i,20-50,10-30,U+ ^Eucalyptus exilipes+/-Corymbia peltata+/-C...,11,Eucalypt Open Woodlands,19,Eucalyptus low open woodlands with tussock grass
17242,40210,level6_sub_association,6,U,Eucalyptus fibrosa subsp. fibrosa,Corymbia xanthope,Corymbia citriodora,Eucalyptus,Dom,Corymbia,...,2.0,0.5-1 m,i,20-50,10-30,U+ ^Eucalyptus fibrosa subsp. fibrosa+/-Corymb...,5,Eucalypt Woodlands,8,Eucalyptus woodlands with a shrubby understorey
17474,41542,level6_sub_association,4,U,Corymbia henryi,Eucalyptus fibrosa subsp. fibrosa,Corymbia citriodora,Corymbia,Dom,Eucalyptus,...,2.0,0.5-1 m,i,20-50,10-30,U+ ^Corymbia henryi+/-Eucalyptus fibrosa subsp...,3,Eucalypt Open Forests,5,Eucalyptus open forests with a grassy understorey
17683,42779,level6_sub_association,6,U,Eucalyptus crebra,Eucalyptus portuensis,Corymbia citriodora,Eucalyptus,Dom,,...,2.0,0.5-1 m,c,50-80,30-70,U+ ^Eucalyptus crebra+/-Eucalyptus portuensis+...,5,Eucalypt Woodlands,9,Eucalyptus woodlands with a tussock grass unde...
17685,40198,level6_sub_association,6,U,Eucalyptus decorticans,Corymbia hendersonii,Corymbia citriodora,Eucalyptus,Dom,Corymbia,...,3.0,1-2 m,c,50-80,30-70,U+ ^Eucalyptus decorticans+/-Corymbia henderso...,5,Eucalypt Woodlands,8,Eucalyptus woodlands with a shrubby understorey
18022,41086,level6_sub_association,4,U,Eucalyptus granitica,Erythrophleum chlorostachys,Corymbia citriodora,Eucalyptus,Dom,Erythrophleum,...,2.0,0.5-1 m,c,50-80,30-70,U+ ^Eucalyptus granitica+/-Erythrophleum chlor...,5,Eucalypt Woodlands,8,Eucalyptus woodlands with a shrubby understorey
18149,41087,level6_sub_association,5,U,Eucalyptus portuensis,Eucalyptus granitica,Corymbia citriodora,Eucalyptus,Dom,,...,2.0,0.5-1 m,c,50-80,30-70,U+ ^Eucalyptus portuensis+/-Eucalyptus graniti...,5,Eucalypt Woodlands,9,Eucalyptus woodlands with a tussock grass unde...

In [40]:
clmns = ['NVISDSC1','NVISDSC2','NVISDSC3','NVISDSC4','NVISDSC5','NVISDSC6']
sum(nvis_qld[clmns].isin(qry).any(axis=1))

0

In [86]:
nvis_nsw.shape

(14325421, 18)

In [89]:
nvis_nsw.groupby('SPATIAL_MIX').agg({'NVISDSC1':'nunique'})

             NVISDSC1
SPATIAL_MIX
                    1
pure             1681
unknown             1

In [62]:
[sum(nvis_nsw.NVISDSC1.isin(qry)),
sum(nvis_nsw.NVISDSC2.isin(qry)),
sum(nvis_nsw.NVISDSC3.isin(qry)),
sum(nvis_nsw.NVISDSC4.isin(qry)),
sum(nvis_nsw.NVISDSC5.isin(qry)),
sum(nvis_nsw.NVISDSC6.isin(qry))]

[263004, 0, 0, 0, 0, 0]

In [63]:
[sum(nvis_qld.NVISDSC1.isin(qry)),
sum(nvis_qld.NVISDSC2.isin(qry)),
sum(nvis_qld.NVISDSC3.isin(qry)),
sum(nvis_qld.NVISDSC4.isin(qry)),
sum(nvis_qld.NVISDSC5.isin(qry)),
sum(nvis_qld.NVISDSC6.isin(qry))]

[0, 0, 0, 0, 0, 0]

In [65]:
[sum(nvis_vic.NVISDSC1.isin(qry)),
sum(nvis_vic.NVISDSC2.isin(qry)),
sum(nvis_vic.NVISDSC3.isin(qry)),
sum(nvis_vic.NVISDSC4.isin(qry)),
sum(nvis_vic.NVISDSC5.isin(qry)),
sum(nvis_vic.NVISDSC6.isin(qry))]

[103897, 0, 0, 0, 0, 0]

In [66]:
sum(nvis_sa.NVISDSC1.isin(qry))

0

In [67]:
sum(nvis_wa.NVISDSC1.isin(qry))

0

In [68]:
sum(nvis_nsw.NVISDSC1.isin(qry))

263004

In [85]:
nvis_qld.head()

,MAPUNT_IDENTIFIER,NO_VEG_DESC,SPATIAL_MIX,NVISDSC1,NVISDSC2,NVISDSC3,NVISDSC4,NVISDSC5,NVISDSC6,VEGPROP1,VEGPROP2,VEGPROP3,VEGPROP4,VEGPROP5,VEGPROP6,DATA_SET_NUMBER,Shape_Length,Shape_Area
0,49300001,1,pure,40003,NaN,NaN,NaN,NaN,NaN,100,0,0,0,0,0,493,744.819069,22846.669202
1,49300003,1,pure,40013,NaN,NaN,NaN,NaN,NaN,100,0,0,0,0,0,493,2532.783728,329740.760841
2,49300003,1,pure,40013,NaN,NaN,NaN,NaN,NaN,100,0,0,0,0,0,493,3221.306102,158238.257063
3,49300003,1,pure,40013,NaN,NaN,NaN,NaN,NaN,100,0,0,0,0,0,493,2113.566259,190882.037094
4,49300003,1,pure,40013,NaN,NaN,NaN,NaN,NaN,100,0,0,0,0,0,493,988.678523,37111.096819